// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import "./globals.css"; // import TailwindCSS hoặc CSS global
import { AuthProvider } from "@/contexts/AuthContext";
import { CartProvider } from "@/contexts/CartContext";
import { ThemeProvider } from "next-themes";
import { Toaster } from "@/components/UI/sonner";
import { serverApi } from "@/lib/server-api";

export const metadata: Metadata = {
  title: "My Store",
  description: "Website bán hàng demo với Next.js",
};

interface User {
  id: string;
  username: string;
  email: string;
  firstName: string;
  lastName: string;
  authenticated: boolean;
  roles: string[];
}

/**
 * Root Layout - Server Component
 * 
 * Fetch user data từ server một lần cho toàn bộ app
 * → Tránh loading state khi F5
 */
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Fetch user data từ server (SSR) - chỉ fetch 1 lần
  const initialUser = await serverApi.get<User>('/users/me');
  
  console.log('[RootLayout] Initial user data:', initialUser);

  return (
    <html lang="vi" suppressHydrationWarning>
      <body className="bg-gray-50 text-gray-900 dark:bg-gray-900 dark:text-white" suppressHydrationWarning>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {/* Pass initialData to AuthProvider */}
          <AuthProvider initialData={initialUser}>
            {/* Children sẽ là nested layouts (shop/admin/staff) */}
            {children}
            
            {/* Toast notifications */}
            <Toaster />
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}